### ISSUE TITLE
how can deploy for testing localy and not following docker's

### ISSUE THREAD

**Issue by TMwrhere** [smallcloudai/refact#101]

**Comment by olegklimov** [comment]
Not sure what you mean, maybe "please tell me how to run Refact server without docker"? Instructions should be right there:

https://github.com/smallcloudai/refact/blob/main/CONTRIBUTING.md 

Please the text is unclear, please tell.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@TMwrhere local installation can always vary by OS platform. You'll need to write which OS you are using, which instruction step is failing/unclear, which error output you are getting (if any), which Python version you are using etc.

Depending on your OS, you might have to install extra dependencies, e.g., Ubuntu 20+ will have problems with mpi4py, and if you look in the [Dockerfile](https://github.com/smallcloudai/refact/blob/fd775f80459e82854332c5a44e0bb73a53cd9c69/Dockerfile#L4-L14), you will likely have to install `mpich` and/or `libmpich-dev` before it succeeds. (NOTE: This is an example, I haven't tried it so I can't tell you if it works)

**Comment by JunXianWu** [comment]
Maybe I can't load model by internal proxy. Can I load model in Dockerfile build?

**Comment by TMwrhere** [comment]
> @TMwrhere local installation can always vary by OS platform. You'll need to write which OS you are using, which instruction step is failing/unclear, which error output you are getting (if any), which Python version you are using etc.
> 
> Depending on your OS, you might have to install extra dependencies, e.g., Ubuntu 20+ will have problems with mpi4py, and if you look in the Dockerfile
> 
> https://github.com/smallcloudai/refact/blob/fd775f80459e82854332c5a44e0bb73a53cd9c69/Dockerfile#L4-L14
> 
> 
> you will likely have to install `mpich` and/or `libmpich-dev` before it succeeds. (NOTE: This is an example, I haven't tried it so I can't tell you if it works)
> If you are following the instructions, and something isn't working, I am sure they'll love a PR that updates the README

i will try that
