### ISSUE TITLE
[Feature] LORA export / more LORA training capabilities

### ISSUE THREAD

**Issue by sammcj** [smallcloudai/refact#104]
I think Refact's strongest selling points are:

1. It's fast, clean web UI.
2. It's ability to be be run 100% offline locally.
3. It's ability to performing training/fine tuning.

For the third I think it would be great to have some more configurability and options, for example being able to name / add notes to a LORA and export it for backups / testing / other instances etc....

It would also be great if it was possible to perform fine tuning / training on other models.

Keep up the great work folks!

**Comment by mitya52** [comment]
We are working on other models finetune, stay tuned
