### ISSUE TITLE
[Bug/Feedback] - Fine tuning UI (Stop button, ETA and Resume)

### ISSUE THREAD

**Issue by sammcj** [smallcloudai/refact#106]
Some general feedback from my observations using the fine tuning feature over the last few days.

You may be aware of these already but I figured I should log them in case not.

- The "Stop" button on the training doesn't work - it stays partially greyed out and clicking on it does nothing. The only way to cancel the training I could find was to kill the container and start it again.
- The ETA(minutes) has been quite wildly off on my machine (Ryzen 7600, 64GB, RTX3090) it startded at 500mins~ and and so far it's been running for around 780mins and only 2/3rds of the way to completion, this is with no other heavy processing or GPU tasks running.
- There doesn't seem to be a way to resume a cancelled (killed/failed) tune from the checkpoints created.

Screenshot if it helps:

![SCR-20230916-hojk](https://github.com/smallcloudai/refact/assets/862951/cabeeb10-1637-4d2e-9697-f219ddedf6f6)

**Comment by olegklimov** [comment]
Enable/disable buttons we've already addressed, should be merged with #109 

> resume a cancelled (killed/failed) tune

That's not possible without also dumping Adam moments, in addition to weights. I mean it's possible, but it's a bit deeper than fixing the high level logic.

@sammcj thanks for taking the time to describe your experience!

**Comment by olegklimov** [comment]
ETA addressing here https://github.com/smallcloudai/refact/issues/110
Status fixing here https://github.com/smallcloudai/refact/issues/117 and https://github.com/smallcloudai/refact/issues/119

Thanks again Sam

**Comment by sammcj** [comment]
Awesome, thank folks!
