### ISSUE TITLE
[ui] Fix ETA

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact#110]
The column is called ETA, but most runs are finished, they don't have an ETA.

Related issue #106 .

Let's call the column "Time"and move ETA below the logs of the current run.

**Comment by oxyplay** [comment]
FIxed in [beta_today](https://github.com/smallcloudai/refact/compare/beta_today)

**Comment by hazratisulton** [comment]
![image](https://github.com/smallcloudai/refact/assets/140423660/8778bc8a-208e-4167-845b-522e20a81b45)
Unclear name "Time" for spent time in minutes.
Some inconsistency: In Logs "time_elapsed" in seconds and next "eta_minutes" in minutes.

**Comment by hazratisulton** [comment]
Nothing changed from previous check.
