### ISSUE TITLE
[finetune] Cannot stop working finetune

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact#117]
![image](https://github.com/smallcloudai/refact/assets/18546213/ab3188d8-6480-4cfc-a949-23c6fd6f6042)

The button is greyed out.

**Comment by hazratisulton** [comment]
> Fixed in [beta_today](https://github.com/smallcloudai/refact/compare/beta_today)
Now Stop button available. but nothing happen: [Screencast from 28-09-23 05:27:21.webm](https://github.com/smallcloudai/refact/assets/140423660/8a592ed1-740e-463b-856d-c8a957385c96)

**Comment by olegklimov** [comment]
should work!
