### ISSUE TITLE
[finetune] Incorrect finetune status

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact#119]
Displaying FAILED status between end previous iteration and starts next iteration
[Screencast from 24-09-23 04:34:54.webm](https://github.com/smallcloudai/refact/assets/140423660/776548f6-3196-4889-ab88-49225b0b95e1)

**Comment by hazratisulton** [comment]
Checked here https://github.com/smallcloudai/refact/compare/beta_today - OK.

**Comment by olegklimov** [comment]
should work

**Comment by hazratisulton** [comment]
Final check - OK.
