### ISSUE TITLE
[gpu filtering] incorrect numbers of accepted and rejected files after rerun GPU filtering

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact#120]
Run GPU filtering: ![image](https://github.com/smallcloudai/refact/assets/140423660/f1066a9f-a77a-4439-a2d2-bcc9fb317d17)
OK
Rerun GPU filtering: ![image](https://github.com/smallcloudai/refact/assets/140423660/55a5764a-3226-49bf-90fb-47cc91ffca27)
There is incorrect numbers of accepted and rejected files.
![image](https://github.com/smallcloudai/refact/assets/140423660/7951f39c-ab0d-4b65-a345-73a6b9a644bf)
![image](https://github.com/smallcloudai/refact/assets/140423660/cc10c678-c4ce-48a2-9e5b-73e9315d0ebe)

**Comment by mitya52** [comment]
backend part fixed in #131

**Comment by oxyplay** [comment]
Frontend part fixed in [beta_today](https://github.com/smallcloudai/refact/compare/beta_today)

**Comment by hazratisulton** [comment]
> backend part fixed in #131
> Frontend part fixed in [beta_today](https://github.com/smallcloudai/refact/compare/beta_today)
Checked - OK.

**Comment by olegklimov** [comment]
Works for me 🤷

**Comment by hazratisulton** [comment]
Works for me with last changes
![image](https://github.com/smallcloudai/refact/assets/140423660/0a2cbbdc-5e51-4cc2-b3f4-76fc072832be)
There is no status and displayed progress bar, but filtering stats is ok
