### ISSUE TITLE
[finetune] INTERRUPTED status is not displaying

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact#121]
Logs says "Interrupted", but status "failed".
![image](https://github.com/smallcloudai/refact/assets/140423660/5f40591b-a3f5-47ad-b67f-192f918ed2c5)

Sometimes "Interrupted" status appear, but after refreshing page it changes to "failed".
![Screenshot from 2023-09-24 04-06-42](https://github.com/smallcloudai/refact/assets/140423660/2f8426eb-5c30-453d-ac6b-8391ce3bfe22)

**Comment by mitya52** [comment]
fixed in #131
