### ISSUE TITLE
[ui] Move model switch

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact#130]
We need to move this combo box over there. Because it only affects new runs. And the way it's positioned now is confusing, because it interferes with the lora switch. 

Lora switch is between "start new model" box above and "start new model" box below.

![IMAGE 2023-09-26 19:02:09](https://github.com/smallcloudai/refact/assets/18546213/6d04ba24-5f57-47d0-b54c-189cc9b8c528)

**Comment by valaises** [comment]
https://github.com/smallcloudai/refact/pull/132

**Comment by valaises** [comment]
Branch was merged. Closing the issue
