### ISSUE TITLE
vscode extension disables auto save on mac

### ISSUE THREAD

**Issue by nanaknketsiah** [smallcloudai/refact#138]
When i enable refact assistant vscode extension everything works fine untill i sign in then auto save is disabled even when i manually enable auto save everytime. I am using mac os silicon chip.

**Comment by olegklimov** [comment]
Hi @nanaknketsiah 

It's the same issue as this one over there https://github.com/smallcloudai/refact-vscode/issues/23

We'll fix it ~next week!
