### ISSUE TITLE
[ui] Check every http fetch result, show errors in a bubble

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact#143]
`/tab-finetune-training-setup` -- if that returns something other than 200 it's not handled.

**Comment by oxyplay** [comment]
branch ui-animations

**Comment by olegklimov** [comment]
No effect visible.

I turn off Wi-Fi, click random places -- no error messages.

**Comment by olegklimov** [comment]
I've seen 1 error message, but I wasn't able to repeat it. Very rare.

**Comment by hazratisulton** [comment]
> No effect visible.
> 
> I turn off Wi-Fi, click random places -- no error messages.
![Screenshot from 2023-10-07 02-19-54](https://github.com/smallcloudai/refact/assets/140423660/172d86b4-3f75-4cbd-8bc2-d9884c9d83c5)

**Comment by hazratisulton** [comment]
Released in v.1.1.0.
