### ISSUE TITLE
finetune failed even without creating run

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact#147]
Tried to start finetune on 2080TI and get error "lora_r":
![image](https://github.com/smallcloudai/refact/assets/140423660/b195420c-5425-4cf6-b4f4-40e0fef5091f)
![image](https://github.com/smallcloudai/refact/assets/140423660/0f689593-d722-4565-821d-4b98fd8f7f5e)

**Comment by olegklimov** [comment]
Error was: "lora_r"

**Comment by JegernOUTT** [comment]
Couldn't reproduce it, can you leave more details? @hazratisulton

**Comment by hazratisulton** [comment]
> Couldn't reproduce it, can you leave more details? @hazratisulton

Nothing specifiс, just added sources. filtered and tried to run finetune with Refact 1.6B.

**Comment by hazratisulton** [comment]
`root@90cd71def5c2:/# ls perm_storage/loras/lora-20230930-010138
log.txt  status.json

root@90cd71def5c2:/# cat perm_storage/loras/lora-20230930-010138/log.txt 
stats: 67 good, 1 too large, 1 generated, 2 vendored
marking 71 files from nextjs-starter-prismic-blog-master.zip to which_set="train", to_db=False
total files 71
dedup...
after dedup 63 files
Reading /perm_storage/cfg/sources_filetypes.cfg
Will not overwrite '/tmp/unpacked-files/train_set.jsonl' because it is exactly the same as the current output
Will not overwrite '/tmp/unpacked-files/test_set.jsonl' because it is exactly the same as the current output
Will not overwrite '/tmp/unpacked-files/database_set.jsonl' because it is exactly the same as the current output
Reading /perm_storage/cfg/finetune.cfg
FAILED: 'lora_r'

90cd71def5c2 Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/refact_enterprise/finetune/finetune_train.py", line 14, in <module>
    main(models_mini_db)
  File "/usr/local/lib/python3.8/dist-packages/refact_data_pipeline/finetune/finetune_train.py", line 387, in main
    raise e
  File "/usr/local/lib/python3.8/dist-packages/refact_data_pipeline/finetune/finetune_train.py", line 374, in main
    finetune(status_dict, models_db)
  File "/usr/local/lib/python3.8/dist-packages/refact_data_pipeline/finetune/finetune_train.py", line 310, in finetune
    cfg = load_finetune_config(models_db)
  File "/usr/local/lib/python3.8/dist-packages/refact_data_pipeline/finetune/finetune_train.py", line 108, in load_finetune_config
    .set_lora_r(user_cfg['lora_r'])
KeyError: 'lora_r'

root@90cd71def5c2:/# cat perm_storage/loras/lora-20230930-010138/status.json 
{
    "started_ts": 1696035709.9567823,
    "worked_steps": 0,
    "worked_minutes": 0,
    "status": "failed",
    "quality": "unknown",
    "error": "'lora_r'"`

**Comment by JegernOUTT** [comment]
The fix https://github.com/smallcloudai/refact/pull/153

**Comment by hazratisulton** [comment]
> The fix #153

Checked - OK.
