### ISSUE TITLE
Rotate server logs

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact#159]
![Image](https://github.com/smallcloudai/refact/assets/18546213/ffb0fa00-dd7d-49f0-9b8b-0d19f83fd172)

Now daily logs are created indefinitely.

**Comment by valaises** [comment]
@olegklimov 
Do you mean limit log files displayed on the screen?

**Comment by olegklimov** [comment]
No, delete old files, a super simple operation.

**Comment by olegklimov** [comment]
done
