### ISSUE TITLE
[ui] Add a convenient link to the next page, after scanning is complete

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact#161]
Add Linux repo and check 54181 C-files.
After 1-2 seconds popup appears.
Go to Finetune tab, but here GPU filtering is inactive untill scaning ends up.
![image](https://github.com/smallcloudai/refact/assets/140423660/ea529d05-71ba-4b5c-b6b4-d940ae2a73d0)
[Screencast from 04-10-23 03:09:26.webm](https://github.com/smallcloudai/refact/assets/140423660/6be60180-addd-4d49-9867-6dbc755d1f32)

**Comment by olegklimov** [comment]
![image](https://github.com/smallcloudai/refact/assets/18546213/d8104928-a5ff-45db-815c-57a5fd63c8fc)

A link underneath this stats can lead to the next page, finetune.

As it implemented currently, inside save_filter_setup() there is `then({ show message})` doesn't make sense, the server only set the flag, it doesn't finish the work when it returns 200 "OK".

**Comment by olegklimov** [comment]
Deleted the message.

**Comment by hazratisulton** [comment]
There remains a case where the button to finetune is already available, and then many files are selected. I go to finetune page, and everything is blocked there until scan is completed:
[Screencast from 07-10-23 02:10:47.webm](https://github.com/smallcloudai/refact/assets/140423660/ff9d7abe-d320-407e-9556-e5fbe4213679)

**Comment by olegklimov** [comment]
Not clear what this video shows. Let's close this. If there are more problems, we'll open a new one.
