### ISSUE TITLE
[ui] Cannot turn LoRA back on

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact#163]
https://github.com/smallcloudai/refact/assets/18546213/7e3200be-0e91-4998-aa96-09e69cad3e76

1. Set a lora,
2. Press "Off",
3. Press "Custom" again,

It forgets what the lora was.

Also @oxyplay I can click anywhere on checkpoint, not just on ⏯️

**Comment by mitya52** [comment]
#166

**Comment by hazratisulton** [comment]
Checked - OK
