### ISSUE TITLE
[finetune] lora_r does not depend on the codebase size which contradicts Refact's official blog article

### ISSUE THREAD

**Issue by justinas-kazanavicius** [smallcloudai/refact#178]
From [Refact's official blog article](https://refact.ai/blog/2023/open-source-fine-tuning-with-refact/):

> LoRA has one important parameter — tensor size, called **lora_r**. It defines how much information LoRA can add to the network. If your codebase is small, the fine-tuning process will see the same data over and over again, many times in a loop. **We found that for a smaller codebase small LoRA tensors work best because it won’t overfit as much — the tensors just don’t have the capacity to fit the limited training set exactly.**

> To pick all the parameters automatically, we have developed a heuristic that calculates a score based on the source files it sees. **This score is then used to determine the appropriate LoRA size**, number of finetuning steps, and other parameters. We have tested this heuristic on several beta test clients, small codebases of several files, and large codebases like the Linux kernel (consisting of about 50,000 useful source files).

However, in the code we only have a single set of parameters for a single score range (0-1000):
https://github.com/smallcloudai/refact/blob/22c7d39e0d339d1d2b0bc99a7937d5aa1e416779/refact_data_pipeline/finetune/finetune_config.py#L178-L185

Is there something I'm missing, or is the blog article incorrect?

**Comment by JegernOUTT** [comment]
This [setup](https://github.com/smallcloudai/refact/blob/ddb6dd7e1b1a57a2022dd9ecc0098b018b8de465/refact_data_pipeline/finetune/finetune_config.py#L170) wasn't robust enough to cover our cases, especially when we use different models for fine-tuning. The main goal was to "memorize" the given codebase and all the weak setups weren't able to meet that criteria good enough

So, we've made a couple of changes in heuristics after playing with them. We decided to keep only dynamic epoch count selection for now. However, we're going to revisit this part after we collect more experience and feedback from our users.
