### ISSUE TITLE
[ui] Clicking LoRAs 2

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact#185]
tab-tunetune.js

`start_log_stream` only called inside `render_runs()`, that in turn only called from 

```
fetch("/tab-finetune-config-and-runs")
        .then(function (response) {
            return response.json();
        })
        .then(function (data) {
            finetune_configs_and_runs = data;
            render_runs();
```

In turn `tab_finetune_config_and_runs` is called every two seconds, or on model switch.

It never works interactively, click => update svg and logs, that's why it so slow.

**Comment by hazratisulton** [comment]
Done v1.1.0
