### ISSUE TITLE
Add Code LLaMA

### ISSUE THREAD

**Issue by klink** [smallcloudai/refact#217]

**Comment by klink** [comment]
please provide description for model capabilities (chat/ code-completion/ fine-tuning), gpu requirements and official links

**Comment by JegernOUTT** [comment]
https://huggingface.co/TheBloke/CodeLlama-7B-fp16
code-completion / finetuning
20Gb+ for finetune, 15Gb+ for inference

**Comment by i-love-doufunao** [comment]
Is there any ETA to support Code Llama fine-tuning?

**Comment by klink** [comment]
It's already live in our nightly docker, you can test it there, and we plan to release it to everyone ~next week.
