### ISSUE TITLE
Could not scan repo with Refact/1.6B selected

### ISSUE THREAD

**Issue by worldemar** [smallcloudai/refact#218]
Environment:
- Debian 12, Docker version 20.10.24+dfsg1, build 297e128
- running smallcloud/refact_self_hosting_enterprise:beta d994fb420232

Steps to reproduce:
- Run container with original [docker-compose.yml](https://github.com/smallcloudai/refact/blob/main/docker-compose.yml)
- Add SSH key 
- Add repo, select more than one language.
- Scan repo selecting `Refact/1.6B` model

Expected result:
- scan would complete successfully

Actual result:
- scan stops less than minute in, showing error `'GPTRefactForCasualLM' object has no attribute '_set_gradient_checkpointing'`

**Comment by JegernOUTT** [comment]
@worldemar I've fixed this issue yesterday (or I believe so), can you check it again if it's reproducing?
