### ISSUE TITLE
When Using Self-Hosted Server VS Code Plugin Does Not Send Requests

### ISSUE THREAD

**Issue by artforlife** [smallcloudai/refact#230]
I was able to get the Refact working via an API key. I was also able to deploy a self-hosted version on a remote server. However, when I change the settings to use the version on the remote server, the Refact chat does not send any requests to it. There is text in the chat textbox, but it does not get sent.

Log inspection on the server does not show that any requests come through from the clicking the "send" button.

Could someone tell me what is happening and how one can fix it?

**Comment by olegklimov** [comment]
Hi @artforlife 

This might be a bug, but to reproduce it we need more information.

Did you use the most recent docker image?

Was it old plugins (no rust) or is it new plugins (with rust)?

It is VS Code or JB? 

Did you change configuration on docker just before you typed something in the chat?

Do you have a chat model running at all?

What does the combo box in chat show -- do you see the chat model there?
