### ISSUE TITLE
Finetune improvement for better performance

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact#246]
User case:
"I might however have overestimated my PC specs since I'm completely capped on both CPU and RAM (GPU seems okay for now). Unfortunately I had to kill training due to RAM limits"
![image](https://github.com/smallcloudai/refact/assets/140423660/a7d36cea-cf83-472b-9eac-b793f8086515)

**Comment by JegernOUTT** [comment]
I'm going to make a small change in regard to this issue soon

**Comment by hazratisulton** [comment]
Checked smallcloud/refact_self_hosting:nightly 
sha256:caf0d0b8cbe153b9e6e5ceef5b974b222c44c56c1103f936ca1fc081ccd753f0. Process finetune takes up 4 Gb.
