### ISSUE TITLE
Re-login automatically after the list of hosted models changes

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact#25]
...to load new server capabilities

**Comment by olegklimov** [comment]
In VS Code you need to hit refresh to get a new list
![image](https://github.com/smallcloudai/refact/assets/18546213/b3a3ca85-88bc-48ec-894c-b856ca4b3a95)

**Comment by mitya52** [comment]
@max @reymondzzzz please give your attention to this issue

**Comment by olegklimov** [comment]
dup https://github.com/smallcloudai/refact/issues/158
