### ISSUE TITLE
more files to process than processes

### ISSUE THREAD

**Issue by assinchu** [smallcloudai/refact#275]
-- 2218 -- 20240118 18:39:31 FTUNE Finetune is failed
-- 2218 -- Exception: Caught AssertionError in DataLoader worker process 0.
-- 2218 -- Original Traceback (most recent call last):
-- 2218 --   File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 252, in _worker_loop
-- 2218 --     fetcher = _DatasetKind.create_fetcher(dataset_kind, dataset, auto_collation, collate_fn, drop_last)
-- 2218 --   File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 79, in create_fetcher
-- 2218 --     return _utils.fetch._IterableDatasetFetcher(dataset, auto_collation, collate_fn, drop_last)
-- 2218 --   File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 21, in __init__
-- 2218 --     self.dataset_iter = iter(dataset)
-- 2218 --   File "/usr/local/lib/python3.10/dist-packages/refact_data_pipeline/finetune_datasource.py", line 127, in __iter__
-- 2218 --     return iter(self._build_pipeline(self._get_files_by_worker()))
-- 2218 --   File "/usr/local/lib/python3.10/dist-packages/refact_data_pipeline/finetune_datasource.py", line 119, in _get_files_by_worker
-- 2218 --     assert len(files) > worker_info.num_workers, "YO have to have more files to process than processes"
-- 2218 -- AssertionError: YO have to have more files to process than processes

**Comment by JegernOUTT** [comment]
Thank you for the issue, the fix will be soon

**Comment by assinchu** [comment]
Thanks for the quick reply . 

I forgot to mention my server spec earlier .

I am running on 4 Nvidia H100 cards and training around 10 files . Still facing the issue . Is there any environmental change I need to do to over come the issue ? Or does it need a code fix from your end .

please let me k is if you need more info in the server

**Comment by JegernOUTT** [comment]
Soon we're going to merge fixes on our side and after that you'll have to update the docker to get the changes

**Comment by hazratisulton** [comment]
Checked smallcloud/refact_self_hosting:nightly 
sha256:caf0d0b8cbe153b9e6e5ceef5b974b222c44c56c1103f936ca1fc081ccd753f0 - OK
