### ISSUE TITLE
401 unauthorised... any additional configs to be put in

### ISSUE THREAD

**Issue by satnair** [smallcloudai/refact#29]
Hi , trying to host this without docker.... Please suggest if I am missing something. 

info:     Uvicorn running on https://0.0.0.0:8008 (Press CTRL+C to quit)INFO:     16.142.51.155:38015 - "GET / HTTP/1.1" 404 Not FoundINFO:     16.142.51.155:38015 - "GET /favicon.ico HTTP/1.1" 404 Not FoundINFO:     16.142.51.155:38015 - "GET / HTTP/1.1" 404 Not FoundINFO:     16.142.51.155:5217 - "GET /v1/login HTTP/1.1" 200 OKINFO:root:running /v1/contrast function=infillINFO:     16.142.51.155:4871 - "POST /v1/contrast HTTP/1.1" 401 UnauthorizedINFO:root:running /v1/contrast function=infillINFO:     16.142.51.155:6519 - "POST /v1/contrast HTTP/1.1" 401 UnauthorizedINFO:root:running /v1/contrast function=infill

**Comment by satnair** [comment]
sorry, further debugging, looks like the model is not getting loaded. 

Error:root:model starcoder/15b loading failed:.. Any suggestions.

**Comment by olegklimov** [comment]
Hi @satnair , are you trying the `main` branch? We are about to merge a big number of changes.

**Comment by olegklimov** [comment]
This repo was "half open source" so far, the code was open, but the development process wasn't very much. We'll switch to completely open development after this big merge. The new version is going to be fantastic!

**Comment by satnair** [comment]
Excellent.. Looking forward...

**Comment by olegklimov** [comment]
It's happening, `monorepo` was merged! Announcement in discord and elsewhere coming up
