### ISSUE TITLE
Maybe hide popup when stats is empty?

### ISSUE THREAD

**Issue by valaises** [smallcloudai/refact#389]
![Image](https://github.com/smallcloudai/refact/assets/140423660/9add3b95-c7e9-4a39-b062-177d3c7ff7cf)

**Comment by hazratisulton** [comment]
smallcloud/refact_self_hosting_enterprise:nightly
Digest: sha256:2b03d671f92e1c82655a7347a212dd3e66ca11b5a49234f2e651d94c52f86bd6
![image](https://github.com/smallcloudai/refact/assets/140423660/f556b3b7-b5d1-4359-84bb-4a05f42c1580)

**Comment by hazratisulton** [comment]
smallcloud/refact_self_hosting_enterprise:nightly
Digest: sha256:3412f1b804c04055eb1622b9c3eb79c027b7763c2465126562c7df3bb051b775 
Fixed
