### ISSUE TITLE
[ui] Adding git repo, warn about trailing '/'

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact#43]
Now the error text is "Error: incorrect url"

**Comment by mitya52** [comment]
@hazratisulton please check if we still have this bug

**Comment by hazratisulton** [comment]
Still have:
[lora_chkpts_appear_bug.webm](https://github.com/smallcloudai/refact/assets/140423660/957e5794-75fd-47a7-9559-394b27101800)

**Comment by hazratisulton** [comment]
Old version:
![Screenshot from 2023-09-06 11-25-41](https://github.com/smallcloudai/refact/assets/140423660/3ddb57ec-ffe3-42ed-a9da-17dc95a7e1c4)
Current version (06.09.23) OK:
![image](https://github.com/smallcloudai/refact/assets/140423660/e1384aed-b145-4b11-b46a-eda051f41cb6)

**Comment by hazratisulton** [comment]
Old version:
![Screenshot from 2023-09-06 11-25-41](https://github.com/smallcloudai/refact/assets/140423660/3ddb57ec-ffe3-42ed-a9da-17dc95a7e1c4)
Current version (06.09.23) OK:
![image](https://github.com/smallcloudai/refact/assets/140423660/e1384aed-b145-4b11-b46a-eda051f41cb6)
