### ISSUE TITLE
[UI] In finetuning, ETA is not completely thought through

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact#50]
When a job is working it looks fine, but completed look like this:

<img width="281" alt="image" src="https://github.com/smallcloudai/refact/assets/18546213/28c8fc16-bd4f-4d9b-b5ee-c016470a21cc">

"1" is meaningless, maybe it should show how much time it took, or hide it, or do something.

**Comment by mitya52** [comment]
@oxyplay we should hide ETA for finished finetune runs
