### ISSUE TITLE
[UI] Interface blocked when starting GPU filtering without waiting for file load

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact#53]
Steps:
Add a big file to the list without waiting for the addition to complete
Immediately scan sources and run GPU filter
Expected result:
Interface should not allow GPU filtering to start until all files have finished loading
Actual result:
GPU filtering starts anyway
An error message "No train files have been provided for filtering" is displayed
Upload files/repos buttons are blocked until refresh page
![image](https://github.com/smallcloudai/refact/assets/140423660/56a919b6-5014-4257-a88c-1f55fc749595)
![image](https://github.com/smallcloudai/refact/assets/140423660/ba05f66a-ade0-48e2-b164-bb96265817b4)

Notes:
Issue occurs regardless of file size, but it's easier to reproduce with big file (~500Mb+)
Issue does not occur when waiting for addition to complete before running GPU filter

**Comment by mitya52** [comment]
@hazratisulton move-filter branch fixed this behavior
