### ISSUE TITLE
JSON Decoding Error in create_tracked_jobs_from_configs: Expecting Value

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact#55]
Two time occures random crash:
![image](https://github.com/smallcloudai/refact/assets/140423660/c7199512-4cb4-4fb1-bcad-8831efb11e26)
Reproducing scenarios currently unknown. The assumption that while one process is writing to a file, another is reading the same file.

**Comment by mitya52** [comment]
we plan to move configs from files to database in near future
config FILES io causes this issue (I hope)

**Comment by olegklimov** [comment]
But maybe we should leave files alone, because we want 1 docker to work without a database (another docker)

**Comment by olegklimov** [comment]
Most likely an empty file

**Comment by olegklimov** [comment]
https://github.com/smallcloudai/refact/pull/113/

**Comment by olegklimov** [comment]
Not actionable, close
