### ISSUE TITLE
Allow renaming of LoRA's Completed Runs

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact#59]
By allowing users to rename their completed runs, they can quickly identify and distinguish between different runs.
- Give names to loras when training, "all files", "only python" - what I would like to see for me last two runs
- Rename existing loras
- When exporting, .zip needs to retain the same name

**Comment by olegklimov** [comment]
I like this idea, also it can ask for a name at a finetune start

**Comment by valaises** [comment]
#320
