### ISSUE TITLE
[UI] Move GPU filtering for finetune to the finetune tab

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact#67]
Looks like this now:

<img width="246" alt="image" src="https://github.com/smallcloudai/refact/assets/18546213/acdcceed-39da-4a95-b703-5ebef934ea7f">

and

<img width="494" alt="image" src="https://github.com/smallcloudai/refact/assets/18546213/33cc28b5-0655-4f78-9d5e-9a33431f0211">

Want to move to finetuning tab, and join with "Start new finetune" box like this:

![image](https://github.com/smallcloudai/refact/assets/18546213/51a92c47-6736-4384-9bb6-0265e69131ec)

**Comment by mitya52** [comment]
@olegklimov addition to this, we should add selection of model to finetune: over finetune "steps"

**Comment by mitya52** [comment]
implemented
