### ISSUE TITLE
Self-Hosted server can't use and WEBUI's GPU show loading model

### ISSUE THREAD

**Issue by JunXianWu** [smallcloudai/refact#76]
WEBUI log
-- 302580 -- 20230816 00:49:00 WEBUI 10.244.43.64:1940 - "POST /v1/contrast HTTP/1.1" 200
-- 302580 -- 20230816 00:49:00 WEBUI    ***  CANCEL  ***  cancelling comp-sCPvuzAjDUXL 488.0ms
-- 302580 -- 20230816 00:49:01 WEBUI comp-s7zqIh7A8aiY model resolve "CONTRASTcode" func "infill" -> "CONTRASTcode/3b/multi" from XXX
-- 302580 -- 20230816 00:49:01 WEBUI 10.244.43.64:27439 - "POST /v1/contrast HTTP/1.1" 200
-- 302580 -- 20230816 00:49:31 WEBUI TIMEOUT comp-s7zqIh7A8aiY

**Comment by olegklimov** [comment]
Hi @JunXianWu !
 
Do you mean the docker doesn't work, and also WebUI shows it's still loading the model? That seems normal, right?

Or do you mean the error message doesn't go through?

Or do you mean the loading status is not visible enough from the plugin UI?

**Comment by mitya52** [comment]
@JunXianWu we need more info about problem. This part of log tells only that model is not working now. It might be loading or some error...please give us full log

**Comment by JunXianWu** [comment]
Maybe I can't load model by internal proxy. Can I load model in Dockerfile build?

**Comment by olegklimov** [comment]
No actionable description
