### ISSUE TITLE
Failures on insufficient GPU memory

### ISSUE THREAD

**Issue by Johnz86** [smallcloudai/refact#94]
This is my local setup:
| NVIDIA-SMI 535.103 | Driver Version: 537.13 | CUDA Version: 12.2 |
|--------------------|------------------------|--------------------|

| GPU | Name | Persistence-M | Bus-Id | Disp.A | Volatile Uncorr. ECC | Fan     | Temp    | Perf    | Pwr:Usage/Cap  | Memory-Usage | GPU-Uti | Compute M | MIG M. |
|-----|------|---------------|--------|--------|----------------------|---------|---------|---------|----------------|--------------|---------|-----------|--------|
| 0   | NVIDIA RTX A2000 Laptop GPU | On | 00000000:01:00.0 | On | N/A | N/A | 49C | P0 | 11W / 40W | 3886MiB / 4096MiB | 2% | Default | N/A |

The container seem to start and load the model:
```
PS C:\Users\z0034zpz> docker run -d --rm -p 8008:8008 --env SERVER_API_TOKEN=LocalTokenInDockerContainer -v perm-storage:/perm_storage --gpus all smallcloud/refact_self_hosting
a455ae67d1b7b829460361bec6d3530629f7d2c1577b5e5c495318d5f378223a
PS C:\Users\z0034zpz> docker logs -f a455

==========
== CUDA ==
==========

CUDA Version 11.8.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

20230906 12:56:00 adding job model-contrastcode-3b-multi-0.cfg
20230906 12:56:00 adding job enum_gpus.cfg
20230906 12:56:00 adding job filetune.cfg
20230906 12:56:00 adding job filetune_filter_only.cfg
20230906 12:56:00 adding job process_uploaded.cfg
20230906 12:56:00 adding job webgui.cfg
20230906 12:56:00 CVD=0 starting python -m self_hosting_machinery.inference.inference_worker --model CONTRASTcode/3b/multi --compile
 -> pid 30
20230906 12:56:00 CVD= starting python -m self_hosting_machinery.scripts.enum_gpus
 -> pid 31
20230906 12:56:00 CVD= starting python -m self_hosting_machinery.webgui.webgui
 -> pid 32
-- 32 -- 20230906 12:56:00 WEBUI Started server process [32]
-- 32 -- 20230906 12:56:00 WEBUI Waiting for application startup.
-- 32 -- 20230906 12:56:00 WEBUI Application startup complete.
-- 32 -- 20230906 12:56:00 WEBUI Uvicorn running on http://0.0.0.0:8008 (Press CTRL+C to quit)
-- 30 -- 20230906 12:56:06 MODEL STATUS loading model
-- 32 -- 20230906 12:56:23 WEBUI Invalid HTTP request received.
-- 30 -- 20230906 12:56:44 MODEL STATUS test batch
20230906 12:57:22 30 finished python -m self_hosting_machinery.inference.inference_worker --model CONTRASTcode/3b/multi @:gpu00, retcode 0
/finished compiling as recognized by watchdog
20230906 12:57:23 CVD=0 starting python -m self_hosting_machinery.inference.inference_worker --model CONTRASTcode/3b/multi
 -> pid 105
-- 105 -- 20230906 12:57:25 MODEL STATUS loading model
-- 105 -- 20230906 12:57:51 MODEL STATUS test batch
-- 32 -- 20230906 12:58:15 WEBUI Invalid HTTP request received.
```
I tried to run the vscode extension with and without api key:
![image](https://github.com/smallcloudai/refact/assets/2708520/9283c403-994c-4670-9cd1-7cba6f7d2f64)
I tried to use the extension, but it is inprogress forever:
![image](https://github.com/smallcloudai/refact/assets/2708520/5f83f6a9-74f6-4a0e-9eda-cf43b4e3143a)
The logs inside the container signal an issue, but do not specify what:
```
-- 32 -- 20230906 13:25:05 WEBUI 127.0.0.1:45898 - "POST /infengine-v1/completions-wait-batch HTTP/1.1" 200
-- 32 -- 20230906 13:25:08 WEBUI Invalid HTTP request received.
```
Only if I launch the webui, then I can see:
![image](https://github.com/smallcloudai/refact/assets/2708520/432b137b-993f-467e-abc0-a2700fc848b0)
``` Required memory exceeds the GPU's memory.```

Could you please improve the logs, that a more detailed messasge is visible and provide clear warning, that there is not enough memory on graphic card?

**Comment by Johnz86** [comment]
I tried it with http, the ```Invalid HTTP request received.``` does no longer appear in logs. The issues is that no inference is happening, and I can not determine from logs or any response, what is the state of the process.
![image](https://github.com/smallcloudai/refact/assets/2708520/1a579f77-1090-440f-8b1c-bae54cbc3d8e)
Is there any way to determine, If I should wait for the inference, or when the process does not work at all?

**Comment by mitya52** [comment]
@Johnz86 you can check error occured in refact.ai below chat (yellow box). Also please give server logs, it should be OOM or something like this.

**Comment by olegklimov** [comment]
model is not loaded (2) -- it can't access the model, according the logs.

I guess the good way to go about solving this -- react to configuration changes faster.

https://github.com/smallcloudai/refact/issues/158
