### ISSUE TITLE
Self hosting with 1.3B model?

### ISSUE THREAD

**Issue by loumalouomega** [smallcloudai/refact#98]
Greetings,

There is any docker image for laucnging the 1.3B (https://refact.ai/blog/2023/introducing-refact-code-llm/) model as self hosted?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@loumalouomega have you run `docker pull smallcloud/refact_self_hosting`?

**Comment by loumalouomega** [comment]
> @loumalouomega have you tried with the latest Docker image `docker pull smallcloud/refact_self_hosting`? The 1.6B model is available.

The image launched is the 3B version, do I need to modify command or it is just as README.md says:

`docker run -d --rm -p 8008:8008 -v perm-storage:/perm_storage --gpus all smallcloud/refact_self_hosting`

**Comment by loumalouomega** [comment]
> > @loumalouomega have you tried with the latest Docker image `docker pull smallcloud/refact_self_hosting`? The 1.6B model is available.
> 
> The image launched is the 3B version, do I need to modify command or it is just as README.md says:
> 
> `docker run -d --rm -p 8008:8008 -v perm-storage:/perm_storage --gpus all smallcloud/refact_self_hosting`

And my GPU is 8Gb , so 2B is the a priori limit

**Comment by loumalouomega** [comment]
> @loumalouomega does it start at all? If you can load the WebUI on localhost you can “add” the 1.6 model

Ah now I understand I can change it from the WebUI, I will try and comment it here. Sorry for the noise.

**Comment by loumalouomega** [comment]
I removed the 3B model and added 1.6, but I think is stuck trying to load the 3B model:

![image](https://github.com/smallcloudai/refact/assets/19991680/c8fc7d43-b66e-4327-a68d-cd63084b6622)

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Strange. Not sure, maybe someone else knows :stuck_out_tongue: 
I'd suggest,

1. Restart the Docker container
	2. See if the config is updated and it loads the correct (1.6) model
	3. Check in the `Server Logs` tab, copy-paste it here if it isn't already working

**Comment by loumalouomega** [comment]
Okay now it works, looking at the log I saw that the model was not downloaded and it took time to be downloaded, my bad. Thanks for everuthing!

**Comment by olegklimov** [comment]
We'll make more visible "model not loaded yet" situation
